apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tiltakspenger-oppslag"
  namespace: "tpts"
  labels:
    "team": "tpts"
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tiltakspenger-oppslag.dev.intern.nav.no
  liveness:
    path: "/isalive"
    initialDelay: 20
  readiness:
    path: "/isready"
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tpts-tiltakspenger-mottak
          namespace: tpts
          cluster: dev-gcp
