apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tiltakspenger-oppslag"
  namespace: "tpts"
  labels:
    "team": "tpts"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/isalive"
    initialDelay: 20
  readiness:
    path: "/isready"
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  ingresses:
    - https://tiltakspenger-oppslag.dev.intern.nav.no
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
